package com.sorted.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ResponseCode {

    // @formatter:off
	SUCCESSFUL("SE_0000", "Successful.", "Successful."),
	ERR_0001("SE_0001", "Something went wrong.", "Something went wrong."),
	INVALID_REQ("SE_0002", "Invalid request.", "Invalid request."),
	MANDATE_CATEGORY("SE_0003", "Category name is mandatory.", "Category name is mandatory."),
	MANDATE_SUB_CATEGORY("SE_0004", "Sub category name is missing.", "Sub category name is missing."),
	INVALID_SUB_CATEGORY("SE_0005", "Invalid sub category.", "Invalid sub category."),
	INVALID_MIN_SUB_CATEGORY("SE_0006", "At least one value is required for sub category.",	"At least one value is required for sub category."),
	MISSING_SUB_CATEGORY_VAL("SE_0007", "Missing sub category value.", "Missing sub category value"),
	INVALID_CATEGORY_SELECTED("SE_0008", "Invalid category selected.", "Invalid category selected."),
	MISSING_PRODUCT_NAME("SE_0009", "Product name is missing.", "Product name is missing."),
	INVALID_PRODUCT_NAME("SE_0010", "Invalid product name.", "Invalid product name."),
	MISSING_PRODUCT_PRICE("SE_0011", "Price is missing.", "Price is missing."),
	INVALID_PRODUCT_MRP("SE_0012", "Invalid product MRP.", "Invalid product MRP."),
	MISSING_QUANTITY("SE_0013", "Quantity is missing.", "Quantity is missing."),
	INVALID_QUANTITY("SE_0014", "Invalid quantity.", "Invalid quantity."),
	CATEGORY_NOT_SELECTED("SE_0015", "Category not selected.", "Category not selected."),
	EMPTY_SUB_CATEGORY("SE_0016", "Select atleast 1 sub-category.", "Select atleast 1 sub-category."),
	EMPTY_ATTRIBUTE("SE_0017", "Attribute is missing.", "Attribute is missing."),
	INVALID_ATTRIBUTE("SE_0018", "Invalid attribute selected.", "Invalid attribute selected."),
	MISSING_PRODUCT_DESCRIPTION("SE_0019", "Product description is missing.", "Product description is missing."),
	INVALID_PRODUCT_DESCRIPTION("SE_0020", "Product description is invalid.", "Product description is invalid."),
	MISSING_ID("SE_0021", "Entity id is missing for update.", "Something went wrong."),
	NO_RECORD("SE_0022", "No record found.", "No record found."),
	NOT_A_LIST("SE_0023", "List is required.", "Something went wrong."),
	MISSING_USER_ID("SE_0024", "User id is missing.", "Requester details missing."),
	MISSING_ROLE_ID("SE_0025", "Role id is missing.", "Requester details missing."),
	MISSING_PRODUCT_ID("SE_0026", "Product id is missing.", "Product id is missing."),
	PRODUCT_NOT_FOUND("SE_0027", "Product not found.", "Product not found."),
	PRODUCT_OUT_OF_STOCK("SE_0026", "This product out of stock.", "This product out of stock."),
	STOCK_LIMIT_REACHED("SE_0029", "Stock limit reached. Additional quantities cannot be added at this time.", "Stock limit reached. Additional quantities cannot be added at this time."),
	MISSING_PRODUCT_QUANTITY("SE_0030", "Product quantity is missing.", "Product quantity is missing."),
	INVAALID_PRODUCT_QUANTITY("SE_0031", "Product quantity is invalid.", "Product quantity is invalid."),
	CART_NOT_FOUND("SE_0032", "First crete a cart for this user by adding an item.", "First crete a cart for this user by adding an item."),
	PASS_VALIDATION_FAILURE_1("SE_0033", "Password must contain atleast one lower case letter", "Password must contain atleast one lower case letter"),
	PASS_VALIDATION_FAILURE_2("SE_0034", "Password must contain atleast one upper case letter", "Password must contain atleast one upper case letter"),
	PASS_VALIDATION_FAILURE_3("SE_0035", "Password must contain atleast one numeric value", "Password must contain atleast one numeric value"),
	PASS_VALIDATION_FAILURE_4("SE_0036", "Password must contain atleast one special character", "Password must contain atleast one special character"),
	PASS_VALIDATION_FAILURE_5("SE_0037", "Password must contain minimum eight characters", "Password must contain minimum eight characters"),
	DUPLICATE_MOBILE("SE_0038", "An account is already created using this mobile no, login or use a different mobile no.", "An account is already created using this mobile no, login or use a different mobile no."),
	DUPLICATE_EMAIL("SE_0039", "This email id is linked to another mobile no.", "This email id is linked to another mobile no."),
	DEFAULT_ROLE_MISSING("SE_0040", "Default role not found.", "Something went wrong."),
	MISSING_OTP("SE_0041", "Please enter otp.", "Please enter otp."),
	INVALID_OTP("SE_0042", "Please enter a valid otp.", "Please enter a valid otp."),
	MISSING_ENTITY("SE_0043", "Entity id is missing.", "Something went wrong."),
	ENTITY_NOT_FOUND("SE_0044", "Entity not found.", "Something went wrong."),
	OTP_EXPIRED("SE_0045", "Otp expired.", "Otp expired."),
	MISSING_FN("SE_0044", "First name is missing.", "First name is missing."),
	MISSING_LN("SE_0045", "Last name is missing.", "Last name is missing."),
	MISSING_MN("SE_0046", "Mobile number is missing.", "Mobile number is missing."),
	MISSING_EI("SE_0047", "Email ID is missing.", "Email ID is missing."),
	MISSING_PASS("SE_0048", "Password is missing.", "Password is missing."),
	INVALID_FN("SE_0049", "Please enter a valid first name.", "Please enter a valid first name."),
	INVALID_LN("SE_0050", "Please enter a valid last name.", "Please enter a valid last name."),
	INVALID_MN("SE_0051", "Please enter a valid mobile number.", "Please enter a valid mobile number."),
	INVALID_EI("SE_0052", "Please enter a valid email ID.", "Please enter a valid first email ID."),
	MISSING_MOBILE("SE_0053", "Mobile no is missing.", "Mobile no is missing."),
	LOGIN_FAILED("SE_0054", "Invalid user name or password.", "Invalid user name or password."),
	USER_BLOCKED("SE_0055", "This account is blocked, please contact customer service.", "This account is blocked, please contact customer service."),
	ROLE_MISSING("SE_0056", "Role not found.", "Something went wrong."),
	USER_NOT_FOUND("SE_0057", "User Not found.", "User Not found."),
	INVALID_SEMISTER("SE_0058", "Invalid branch.", "Invalid semister selected."),
	INVALID_BRANCH("SE_0059", "Invalid branch.", "Branch not found."),
	ENTITY_DEFINATION_INCOMPLETE("SE_0060", "Entity defination missing in EntityDetails.", "Something went wrong."),
	ALREADY_SIGNED_UP("SE_0061", "This mobile no is already used, please sign in or use a different mobile no.", "This mobile no is already used, please sign in or use a different mobile no."),
	MISSING_REF_ID("SE_0062", "Reference id is missing.", "Reference id is missing."),
	MSSING_CUST_DEF_ROLE("SE_0063", "Customer default role not found.", "Something went wrong."),
	MISSING_PROCESS_TYPE("SE_0064", "Process type missing", "Something went wrong."),
	INVALID_RESEND_REQUEST("SE_0065", "No OTP found for resend process.", "Please go back and start the process again."),
	SESSION_EXPIRED("SE_0066", "Session expired.", "Session expired, please restart the process."),
	BR_OLD_PASSWORD("SE_0067", "Use a different password.", "Use a different password."),
	CATEGORY_NOT_FOUND("SE_0068", "Selected category not found.", "Selected category not found."),
	INVALID_CATEGORY("SE_0069", "Invalid category name.", "Invalid category name."),
	PLEASE_SELECT_SELLER("SE_0070", "Please select seller", "Please select seller"),
	SELLER_NOT_FOUND("SE_0071", "Seller not found", "Seller not found"),
	NO_ITEMS("SE_0072", "Items list is empty.", "Something went wrong."),
	ITEM_NOT_FOUND("SE_0073", "Item not found.", "Something went wrong."),
	SELLER_STATUS_UNCHANGED("SE_0074", "Seller status unchanged", "Seller status unchanged"),
	MANDATE_MRP("SE_0075", "MRP is missing.", "MRP is missing."),
	SELLER_ID_MANDATE("SE_0076", "Seller ID is mandatory", "Something went wrong"),
	ACTION_NOT_ALLOWED("SE_0077", "Action not allowed", "Something went wrong"),
	MANDATE_SP("SE_0078", "Selling price is missing.", "Selling price is missing."),
	INVALID_SELLING_PRICE("SE_0079", "Invalid Selling Price.", "Invalid Selling Price."),
	ACCESS_DENIED("SE_0080", "Access Denied.", "Access Denied."),
	PROMT_SIGNUP("SE_0081", "Hold on! You need to log in or sign up to buy this. Join us—it's quick and easy!", "Hold on! You need to log in or sign up to buy this. Join us—it's quick and easy!"),
	CART_EMPTY("SE_0082", "Cart is empty, please add items.", "Cart is empty, please add items."),
	OUT_OF_STOCK("SE_0083", "Sorry! Your requested item ran out of stock.", "Sorry! Your requested item ran out of stock."),
	DELETED_PRODUCT("SE_0084", "Product might be deleted.", "One/Few product/s currently unavailable, please refresh and try again."),
	FEW_OUT_OF_STOCK("SE_0085", "Oops! Few items just went out of stock, please refresh and try again.", "Oops! Few items just went out of stock, please refresh and try again."),
	MISSING_ADDRESS("SE_0086", "Address is missing.", "Address is missing."),
	MANDATE_STREET("SE_0087", "Street 1 is mandatory.", "Street 1 is mandatory."),
	INVALID_STREET("SE_0088", "Please provide valid Street 1.", "Please provide valid Street 1."),
	INVALID_STREET_2("SE_0089", "Please provide valid Street 2.", "Please provide valid Street 2."),
	MANDATE_LANDMARK("SE_0090", "Landmark is mandatory.", "Landmark is mandatory."),
	INVALID_LANDMARK("SE_0091", "Please provide valid Landmark.", "Please provide valid Landmark."),
	MANDATE_CITY("SE_0091", "City is mandatory.", "City is mandatory."),
	INVALID_CITY("SE_0092", "Please provide valid City.", "Please provide valid City."),
	MANDATE_STATE("SE_0093", "City is mandatory.", "City is mandatory."),
	INVALID_STATE("SE_0094", "Please provide valid City.", "Please provide valid City."),
	MANDATE_PINCODE("SE_0095", "Pincode is mandatory.", "Pincode is mandatory."),
	INVALID_PINCODE("SE_0096", "Please provide valid Pincode.", "Please provide valid Pincode."),
	MANDATE_ADDRESS_TYPE("SE_0097", "Please select address type.", "Please select address type."),
	MANDATE_OTHER_ADDRESS_DESC("SE_0098", "Please input other address type description.", "Please input other address type description."),
	INVALID_OTHER_ADDRESS_DESC("SE_0099", "Invalid other address type description.", "Invalid input other address type description."),
	MANDATE_CUST_USER_ID("SE_0100", "Customer user id is missing.", "Customer user id is missing."),
	VARIENT_NOT_FOUND("SE_0101", "Varient does not exists.", "Varient does not exists."),
	DUPLICATE_VARIENT("SE_0102", "Varient already exists with this name.", "Varient already exists with this name."),
	INVALID_VARIENT_NAME("SE_0103", "Invalid varient name.", "Invalid varient name."),
	MANDATE_SELLER_NAME("SE_0104", "Seller name is mandatory.", "Seller name is mandatory."),
	INVALID_SELLER_NAME("SE_0105", "Invalid seller name.", "Invalid seller name."),
	MANDATE_PAN_NO("SE_0106", "PAN is mandatory.", "PAN is mandatory."),
	INVALID_PAN_NO("SE_0107", "Invalid PAN.", "Invalid PAN."),
	MANDATE_SPOC("SE_0108", "Please provide atleast one spoc person detail.", "Please provide atleast one spoc person detail."),
	MANDATE_SPOC_FNAME("SE_0109", "Spoc person first name is missing.", "Spoc person first name is missing."),
	INVALID_SPOC_FNAME("SE_0110", "Spoc person first name is invalid.", "Spoc person first name is invalid."),
	MANDATE_SPOC_LNAME("SE_0109", "Spoc person last name is missing.", "Spoc person last name is missing."),
	INVALID_SPOC_LNAME("SE_0110", "Spoc person last name is invalid.", "Spoc person last name is invalid."),
	MANDATE_SPOC_MAIL("SE_0111", "Spoc person email is missing.", "Spoc person email is missing."),
	INVALID_SPOC_MAIL("SE_0112", "Spoc person email is missing.", "Spoc person email is missing."),
	MANDATE_SPOC_PHONE("SE_0113", "Spoc person phone is missing.", "Spoc person phone is missing."),
	INVALID_SPOC_PHONE("SE_0114", "Spoc person phone is missing.", "Spoc person phone is missing."),
	MANDATE_SPOC_DESIGNATION("SE_0115", "Spoc person designation is missing.", "Spoc person designation is missing."),
	INVALID_SPOC_DESIGNATION("SE_0116", "Spoc person designation is invalid.", "Spoc person designation is invalid."),
	DUPLICATE_SPOC_PHONE("SE_0117", "Please use unique phone number for a SPOC.", "Please use unique phone number for a SPOC."),
	MARK_PRIMARY("SE_0118", "Please select a primary SPOC.", "Please select a primary SPOC."),
	MANDATE_BANK_DETAILS("SE_0119", "Bank details are missing.", "Bank details are missing."),
	MANDATE_ACC_NO("SE_0120", "Account no is missing.", "Account no is missing."),
	MANDATE_IFSC("SE_0121", "IFSC code is missing.", "IFSC code is missing."),
	MANDATE_BRANCH_NAME("SE_0122", "Branch name is missing.", "Branch name is missing."),
	INVALID_BRANCH_NAME("SE_0123", "Branch name is invalid.", "Branch name is invalid."),
	MANDATE_BANK_NAME("SE_0124", "Bank name is missing.", "Bank name is missing."),
	INVALID_BANK_NAME("SE_0125", "Bank name is invalid.", "Bank name is invalid."),
	NOT_A_MAP("SE_0126", "Map is required.", "Something went wrong."),
	DUPLICATE_SE_MOBILE("SE_0127", "Primary contact number is already registered under a different seller.", "Primary contact number is already registered under a different seller."),
	DUPLICATE_USER_MOBILE("SE_0128", "Already an account is created using primary mobile no.", "Already an account is created using primary mobile no."),
	DUPLICATE_USER_EMAIL("SE_0129", "Already an account is created using primary email id.", "Already an account is created using primary email id."),
	MANDATE_SERVICEABLE_PINCODE("SE_0130", "Please input serviceablle pincodes, this can be modified later.", "Please input serviceablle pincodes, this can be modified later."),
	INVALID_SELLER_STATUS("SE_0131", "Invalid seller status.", "Something went wrong."),
	MISSING_PRIMARY_SPOC("SE_0132", "No primary SPOC.", "Something went wrong."),
	RECIPIENT_MISSING("SE_0133", "Recipient email is missing.", "Recipient email is missing."),
	SUBJECT_IS_MISSING("SE_0134", "Email subject is missing.", "Email subject is missing."),
	CONTENT_IS_MISSING("SE_0135", "Email content is missing.", "Email content is missing."),
	TEMPLATE_IS_MISSING("SE_0136", "Email template is missing.", "Email template is missing."),
	MISSING_CATAGORY("SE_0137", "Catagory not found.", "Something went wrong."),
	CANNOT_SECURE("SE_0138", "This item cannot be secured.", "This item cannot be secured."),
	MISSING_DEF_SELLER_PLAN("SE_0139", "Default seller plan is missing.", "Default seller plan is missing."),
	MISSING_DELIVERY_ADD("SE_0140", "Please add or select a delivery address.", "Please add or select a delivery address."),
	ADDRESS_NOT_FOUND("SE_0141", "Address not found.", "Address not found."),
	MISSING_RETURN_DATE("SE_0142", "Return date is missing.", "Please select a return date."),
	INVALID_RETURN_DATE("SE_0143", "Return date is invalid.", "Return date is invalid."),
	INVALID_AMOUNT("SE_0144", "Invalid Amount", "Invalid Amount"),
	PG_ORDER_GEN_FAILED("SE_0145", "PG order generation failed", "Something went wrong."),
	MANDATE_ORDER_ID("SE_0146", "Order id is mandatory", "Something went wrong."),
	PG_BAD_REQ("SE_0147", "PG mandatory req param missing", "Something went wrong."),
	SP_MAX_MRP("SE_0148", "Selling price cannot be greater than MRP.", "Selling price cannot be greater than MRP."),
	INVALID_FILE_TYPE("SE_0149", "Invalid file type.", "Invalid file type."),
	IMAGES_NOT_FOUND("SE_0150", "Image/s not found.", "Image/s not found."),
	DOC_IDS_MISSING("SE_0151", "Invalid document details.", "Invalid document details."),
	MISSING_PRODUCTS("SE_0152", "Missing product details.", "Missing product details."),
	ALREADY_DELETED("SE_0153", "This product is already deleted.", "This product is already deleted."),
	PRODUCT_DELETED("SE_0154", "Product deleted successfully.", "Product deleted successfully."),
	PASSWORD_ALREADY_RESET("SE_0155", "Password already set.", "User has already reset the password, please ask to login or proceed with forgot pass."),
	RESEND_SUCCESS("SE_0156", "Mail sent with a new password.", "Mail sent with a new password."),
	MANDATE_SEMISTER("SE_0157", "Semister is missing.", "Semister is missing."),
	MANDATE_SEMESTER_DESC("SE_0158", "Semester description is missing.", "Semester description is missing."),
	INVALID_COLLEGE_NAME("SE_0159", "Invalid characters in college name.", "Invalid characters in college name."),
	UNAUTHORIZED("SE_0160", "Unauthorized.", "Unauthorized, token expired."),
	INVALID_ORDER_STATUS("SE_0161", "Invalid order status.", "Invalid order status."),
	NOT_DELIVERIBLE("SE_0162", "Delivery isn't available at this location yet. Please try another pincode!", "Delivery isn't available at this location yet. Please try another pincode!"),
	UNTRUSTED_RESPONSE("SE_0163", "Invalid or untrusted details provided.", "Something went wrong"),
	SELECT_PINCODE("SE_0164", "Please select a pincode to view products available for delivery in your area.", "Please select a pincode to view products available for delivery in your area."),
	ORDER_PLACED("SE_0165", "Order placed successfully.", "Order placed successfully."),
	INVALID_SELLER_FOR_ORDER("SE_0166", "Order does not belong to this shop.", "Order does not belong to this shop."),
	READY_FOR_DISPATCH("SE_0167", "Request sent to delivery partner for pickup.", "Request sent to delivery partner for pickup."),
	MANDATE_COLLEGE_NAME("SE_0168", "College name is missing.", "College name is missing."),
	MANDATE_PHONE("SE_0169", "Phone No is mandatory.", "Phone No is mandatory."),
	INVALID_PHONE("SE_0170", "Please provide valid Phone No.", "Please provide valid Phone No."),
	MULTIPLE_SELLERS("SE_0171", "Multiple sellers for single order.", "Something went wrong, please contact customer support."),
	MANDATE_GENDER("SE_0172", "Gender not selected.", "Gender selection is mandatory."),
	ADD_ALREADY_DELETED("SE_0173", "This address is already deleted.", "This address is already deleted."),
	MISSING_ORDER_ID("SE_0174", "Order id is missing.", "Order id is missing."),
	ORDER_NOT_FOUND("SE_0175", "Order not found.", "No order found with the specified ID."),
	MISSING_SETTLEMENT_DETAILS("SE_0176", "Settlement details are missing.", "Settlement details are missing."),
	SETTLEMENT_NOT_ALLOWED("SE_0177", "Settlement not allowed.", "Settlement is not allowed for the current order status."),
	ALREADY_SETTLED("SE_0178", "Already settled.", "This order has already been settled."),
	MISSING_PAYMENT_MODE("SE_0179", "Payment mode is missing.", "Please specify a payment mode."),
	INVALID_PAYMENT_AMOUNT("SE_0180", "Invalid payment amount.", "Payment amount must be greater than zero."),
	AMOUNT_VALIDATION_FAILED("SE_0181", "Amount validation failed.", "Settlement amount must match the seller fee."),
	MISSING_VPA("SE_0182", "VPA is missing.", "Virtual Payment Address is required for UPI payments."),
	MISSING_ACCOUNT_NUMBER("SE_0183", "Account number is missing.", "Account number is required for bank transfers."),
	MISSING_IFSC_CODE("SE_0184", "IFSC code is missing.", "IFSC code is required for bank transfers."),
	INVALID_IFSC_CODE("SE_0185", "Invalid IFSC code.", "Please provide a valid IFSC code."),
	MISSING_REWARD_NAME("SE_0186", "Reward name is missing.", "Reward name is missing."),
	MISSING_REWARD_TRIGGER_EVENT("SE_0187", "Reward trigger event is missing.", "Reward trigger event is missing."),
	MISSING_REWARD_SCOPE("SE_0188", "Reward scope is missing.", "Reward scope is missing."),
	MISSING_REWARD_DETAILS("SE_0189", "Reward details are missing.", "Reward details are missing."),
	MISSING_AUDIENCE_FOR_SPECIFIC_SCOPE("SE_0190", "Audience user IDs are missing for specific scope.", "Audience user IDs are missing for specific scope."),
	MISSING_REWARD_TYPE("SE_0191", "Reward type is missing.", "Reward type is missing."),
	MISSING_REWARD_VALUE("SE_0192", "Reward value is missing.", "Reward value is missing."),
	INVALID_REWARD_PERCENTAGE_VALUE("SE_0193", "Invalid reward percentage value.", "Invalid reward percentage value."),
	INVALID_REWARD_VALUE("SE_0194", "Invalid reward value.", "Invalid reward value."),
	MISSING_REWARD_VALIDITY_TYPE("SE_0195", "Reward validity type is missing.", "Reward validity type is missing."),
	MISSING_REWARD_VALIDITY_DATES("SE_0196", "Reward validity dates are missing.", "Reward validity dates are missing."),
	INVALID_REWARD_VALIDITY_DATES("SE_0197", "Invalid reward validity dates.", "Invalid reward validity dates."),
	INVALID_REWARD_VALIDITY_DAYS("SE_0198", "Invalid reward validity days.", "Invalid reward validity days."),
	MISSING_TRANSACTION_ID("SE_0199", "Transaction ID is missing.", "Transaction ID is missing."),
	MISSING_CHEQUE_NUMBER("SE_0200", "Cheque number is missing.", "Cheque number is required for cheque payments."),
	MISSING_BENEFICIARY_NAME("SE_0201", "Beneficiary name is missing.", "Please provide the beneficiary name."),
	MISSING_TRANSACTION_DATE("SE_0202", "Transaction date is missing.", "Please provide the transaction date."),
	INVALID_TRANSACTION_DATE("SE_0203", "Invalid transaction date.", "Transaction date must not be in the future."),
	MISSING_TRANSACTION_SCREENSHOT("SE_0204", "Transaction screenshot is missing.", "Please provide a screenshot of the transaction."),
	INTERNAL_SERVER_ERROR("SE_0205", "Internal server error.", "An unexpected error occurred. Please try again later."),
	INVALID_GST_NO("SE_0206", "Invalid GSTIN.", "Invalid GSTIN."),
	NO_OPERATIONAL_SELLER("SE_0207", "Store is closed, please try again later.", "Store is closed, please try again later."),
	MANDATE_GROUP("SE_0208", "Missing or Invalid group.", "Missing or Invalid group."),
	MISSING_RETURN_ITEMS("SE_0209", "Missing return items.", "Something went wrong, please contact customer care."),
	MISSING_TIME_SLOT("SE_0210", "Please select a time slot.", "Something went wrong, please contact customer care."),
	NOT_SECURED_ITEM("SE_0211", "Few/All of the selected items were not secured.", "Something went wrong, please contact customer care."),
	INVALID_STATUS_FOR_SECURE_RETURN("SE_0212", "Invalid order state for return.", "Something went wrong, please contact customer care."),
	INVALID_ITEM_STATUS_FOR_SECURE_RETURN("SE_0213", "Invalid item state for return.", "Something went wrong, please contact customer care."),
	SELLER_NOT_FOUND_FOR_SECURE_RETURN("SE_0214", "Seller not found.", "Something went wrong, please contact customer care."),
	NOT_OPERATIONAL_FOR_SECURE_RETURN("SE_0215", "Not Operational for Secure Return, please select a different date.", "Not Operational for Secure Return, please select a different date."),
	INVALID_RETURN_ITEMS("SE_0216", "Few items not found for return", "Something went wrong, please contact customer care."),
	MISSING_PICKUP_ADD("SE_0217", "Please add or select a pickup address.", "Please add or select a pickup address."),
	MISSING_CATEGORY_NAME("SE_0218", "Missing Category Name.", "Missing Category Name."),
	MISSING_GROUPS("SE_0219", "Missing Groups.", "Missing Groups."),
	MANDATE_EDUCATION_LEVEL("SE_0220", "Missing Education Level.", "Missing Education Level."),
	MANDATE_EDUCATION_LEVEL_DETAILS("SE_0221", "Missing Education Details.", "Missing Education Details."),
	MANDATE_EDUCATION_ID("SE_0222", "Missing Education Details Id.", "Missing Education Details Id."),
	MISSING_MANDATE_EDUCATION_DETAILS("SE_0223", "Missing mandatory education details.", "Missing mandatory education details."),
	MANDATE_COMBO_NAME("SE_0224", "Missing combo name.", "Missing combo name."),
	MANDATE_COMBO_DESCRIPTION("SE_0225", "Missing combo description.", "Missing combo description."),
	MANDATE_COMBO_PRODUCTS("SE_0226", "Missing combo items.", "Missing combo items."),
	MANDATE_COMBO_PRICE("SE_0227", "Missing combo price.", "Missing combo price."),
	INVALID_PRODUCT_IDS("SE_0228", "Invalid products selected.", "Invalid products selected."),
	MISSING_DESCRIPTION("SE_0229", "Description is missing.", "Description is missing."),
	RESTRICTED_LOCATION("SE_0230", "Non-deliverable location. If you’re inside campus or hostel, please select the nearest entry gate.", "Non-deliverable location. If you’re inside campus or hostel, please select the nearest entry gate."),
	MANDATE_FIRST_NAME("SE_0231","First name is missing.", "First name is missing."),
	MANDATE_LAST_NAME("SE_0232","Last name is missing.", "Last name is missing."),
	INVALID_DISCOUNT_TYPE("SE_0233", "Invalid discount type.", "Invalid discount type."),
	MISSING_COUPON_CODE("SE_0234", "Coupon code is missing.", "Coupon code is missing."),
	INVALID_COUPON_CODE("SE_0235", "Invalid coupon code.", "Invalid coupon code."),
	MISSING_COUPON_NAME("SE_0236", "Coupon name is missing.", "Coupon name is missing."),
	MISSING_COUPON_START_DATE("SE_0237", "Coupon start date is missing.", "Coupon start date is missing."),
	MISSING_COUPON_END_DATE("SE_0238", "Coupon end date is missing.", "Coupon end date is missing."),
	MISSING_COUPON_DESC("SE_0239", "Coupon description is missing.", "Coupon description is missing."),
	MISSING_COUPON_DISCOUNT_TYPE("SE_0240", "Coupon discount type is missing.", "Coupon discount type is missing."),
	INVALID_COUPON_DATE_RANGE("SE_0241", "Invalid coupon date range.", "Invalid coupon date range."),
	MISSING_COUPON_DESCRIPTION("SE_0242", "Coupon description is missing.", "Coupon description is missing."),
	MISSING_COUPON_DISCOUNT_VALUE("SE_0243", "Coupon discount value is missing.", "Coupon discount value is missing."),
	INVALID_COUPON_DISCOUNT_VALUE("SE_0244", "Invalid coupon discount value.", "Invalid coupon discount value."),
	MISSING_COUPON_DISCOUNT_PERCENTAGE("SE_0245", "Coupon discount percentage is missing.", "Coupon discount percentage is missing."),
	INVALID_COUPON_DISCOUNT_PERCENTAGE("SE_0246", "Invalid coupon discount percentage.", "Invalid coupon discount percentage."),
	INVALID_COUPON_MAX_DISCOUNT("SE_0247", "Invalid coupon max discount.", "Invalid coupon max discount."),
	MISSING_COUPON_SCOPE("SE_0248", "Coupon scope is missing.", "Coupon scope is missing."),
	MISSING_COUPON_ASSIGNED_TO_USERS("SE_0249", "Coupon assigned to users is missing.", "Coupon assigned to users is missing."),
	COUPON_CODE_EXISTS("SE_0250", "Coupon code already exists.", "Coupon code already exists."),
	NO_ITEMS_IN_CART("SE_0251", "No items in cart.", "No items in cart."),
	COUPON_CODE_NOT_ACTIVE("SE_0252", "Inactive coupon code.", "Inactive coupon code."),
	COUPON_CODE_NOT_STARTED("SE_0253", "Coupon code is not started.", "Coupon code is not started."),
	COUPON_CODE_EXPIRED("SE_0254", "Coupon code is expired.", "Coupon code is expired."),
	COUPON_CODE_ALREADY_USED("SE_0255", "Coupon code is already used.", "Coupon code is already used."),
	COUPON_CODE_NOT_FOUND("SE_0256", "Coupon code not found.", "Coupon code not found."),
	DELIVERY_ALREADY_FREE("SE_0257", "Delivery is already free on this order.", "Delivery is already free on this order."),
	INVALID_REFERRAL_CODE("SE_0258", "Invalid Referral Code.", "Invalid Referral Code."),
	REFERRAL_NOT_APPLICABLE("SE_0259", "Referral not applicable.", "Referral not applicable."),
	REFERRAL_CODE_EXISTS("SE_0260", "Referral code already exists.", "Referral code already exists."),
	REFERRAL_EXISTS("SE_0261", "Referral code already exists for this user.", "Referral code already exists for this user."),
	MISSING_COMBO("SE_0262", "This combo is missing.", "This combo is missing."),
	COMBO_ITEM_NOT_AVAILABLE("SE_0263", "Few items in this combo are not available.", "Few items in this combo are not available."),
	AMBASSADOR_COUPON_EXISTS("SE_0264", "Ambassador coupon code already exists.", "Ambassador coupon code already exists."),
	MISSING_RECOMMENDER_TYPE("SE_0265", "Recommender type is missing.", "Recommender type is missing."),
	MISSING_RECOMMENDER_DETAILS("SE_0266", "Recommender details is missing.", "Recommender details is missing."),
	MISSING_RECOMMENDATIONS("SE_0267", "Recommender recommendations is missing.", "Recommender recommendations is missing."),
	MANDATE_PRODUCT_ID("SE_0268", "Missing product id.", "Missing product id."),
	MANDATE_TITLE("SE_0269", "Missing title.", "Missing title."),
	MANDATE_TEXT("SE_0270", "Missing text.", "Missing text."),
	INVALID_RATING("SE_0271", "Invalid rating.", "Invalid rating."),
	MISSING_TITLE("SE_0272", "Title is missing.", "Title is missing."),
	MISSING_REVIEW_TEXT("SE_0273", "Review text is missing.", "Review text is missing."),
	MANDATE_PRODUCT_MASTER_ID("SE_0274", "Missing product master id.", "Missing product master id."),
	PRODUCT_MASTER_NOT_FOUND("SE_0275", "Product master not found.", "Product master not found."),
	PRODUCT_IN_STOCK("SE_0276", "Product is in stock, please place your order.", "Product is in stock, please place your order."),
	LOCATION_NOT_FOUND("SE_0277", "Location not found.", "Location not found."),
	MISSING_RATING_OR_AMOUNT("SE_0278", "Either rating or amount must be provided.", "Please provide either a rating (1-5) or a refund amount."),
	INVALID_RATING_RANGE("SE_0279", "Rating must be between 1 and 5.", "Rating must be between 1 and 5."),
	SECURE_RETURN_ALREADY_SCHEDULED("SE_0280", "A secure return is already scheduled.", "A secure return is already scheduled."),
	MISSING_SECURE_RETURN_ID("SE_0281", "Secure return id is missing.", "Secure return id is missing."),
	MISSING_SECURE_ITEMS("SE_0282", "Secure items are missing.", "Secure items are missing."),
	MISSING_ORDER_ITEM_ID("SE_0283", "Order item id is missing.", "Order item id is missing."),
	MISSING_GRADE("SE_0284", "Grade is missing.", "Grade is missing."),
	MISSING_GRADE_REMARKS("SE_0285", "Grade remarks is missing.", "Grade remarks is missing."),
	MISSING_SECURE_ITEM_IMAGES("SE_0286", "Secure item images are missing.", "Secure item images are missing."),
	INVALID_SECURE_RETURN_ID("SE_0287", "Invalid secure return id.", "Invalid secure return id."),
	INVALID_SECURE_RETURN_STATUS("SE_0288", "Invalid secure return status.", "Invalid secure return status."),
	SECURE_RETURN_RESCHEDULE_LIMIT_EXCEEDED("SE_0289", "Secure return reschedule limit exceeded.", "Secure return reschedule limit exceeded."),
	RETURN_DATE_RANGE_EXCEEDED("SE_0290", "Return date range exceeded.", "Return date range exceeded."),
	INVALID_TOKEN("SE_0291", "Invalid or expired token.", "Invalid or expired confirmation link."),
	PICKUP_DATE_PASSED("SE_0292", "Pickup date has passed.", "The scheduled pickup date has already passed."),
	;
	// @formatter:on

    private final String code;
    private final String errorMessage;
    private final String userMessage;
}
