name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches: [master]
  release:
    types: [published]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_PACKAGES_TOKEN
    
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.6
    
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true
      env:
        GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Docker
      run: |
        # Update packages
        sudo apt-get update
        
        # Install dependencies
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        
        # Add Docker's official GPG key
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        
        # Add Docker repository
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        
        # Update packages again
        sudo apt-get update
        
        # Install Docker
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        
        # Add current user to docker group
        sudo usermod -aG docker $USER
        
        # Fix Docker socket permissions
        sudo chmod 666 /var/run/docker.sock
        
        # Verify Docker installation
        docker --version
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/gokuforever/portal-service
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=branch
          type=sha
          latest
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to Production Server
      run: |
        echo "======== DEPLOYMENT STARTED ========"
        
        # Ensure config directory exists
        echo "*** Step 1: Checking config directory ***"
        mkdir -p /home/ubuntu/studeaze/config
        
        # Check if the files exist
        echo "*** Step 2: Listing files in config directory ***"
        echo "Files in /home/ubuntu/studeaze/config:"
        ls -la /home/ubuntu/studeaze/config/ || echo "Error listing files"
        
        # Stop and remove existing container if it exists
        echo "*** Step 3: Stopping existing container ***"
        docker stop portal-service || echo "No container to stop"
        docker rm portal-service || echo "No container to remove"
        
        # Pull latest image
        echo "*** Step 4: Pulling latest image ***"
        docker pull ghcr.io/gokuforever/portal-service:latest
        pull_status=$?
        echo "Pull status: $pull_status"
        
        # Run the container with proper configuration
        echo "*** Step 5: Starting container ***"
        docker run -d \
          --name portal-service \
          --restart always \
          -p 443:443 \
          -e SE_ENV=/app/config \
          -e SPRING_PROFILES_ACTIVE=prod \
          --mount type=bind,source=/home/ubuntu/studeaze/config,target=/app/config \
          --mount type=bind,source=/home/ubuntu/api.studeaze.in.keystore.p12,target=/app/ssl/api.studeaze.in.keystore.p12 \
          ghcr.io/gokuforever/portal-service:latest
        run_status=$?
        echo "Run status: $run_status"
        
        # Verify the mount
        echo "*** Step 6: Verifying mounts ***"
        echo "Docker mounts:"
        docker inspect portal-service | grep -A 10 Mounts || echo "Failed to inspect container"
        
        # Check if files are visible inside the container
        echo "*** Step 7: Checking files inside container ***"
        echo "Listing all files in /app/config:"
        docker exec portal-service ls -la /app/config/ || echo "Failed to list files in container"
        
        # Check if the specific file is visible inside the container
        echo "*** Step 8: Checking for portal-prod.properties ***"
        echo "Looking for portal-prod.properties:"
        docker exec portal-service ls -la /app/config/portal-prod.properties || echo "portal-prod.properties not found in container"
        
        echo "======== DEPLOYMENT COMPLETED ========" 